language: generic 

sudo : required

services:
   - docker

before_install:
   - docker build -t jfsanin/docker-hello-world -f Dockerfile.dev .

script:
   - docker run -e CI=true jfsanin/docker-hello-world npm run test -- --coverage
